# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08e0909f65381451afd52709842ef151"
name = "Option Remove App"
handle = "option-remove-app"
application_url = "https://openings-simulation-blocking-rational.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://openings-simulation-blocking-rational.trycloudflare.com/auth/callback", "https://openings-simulation-blocking-rational.trycloudflare.com/auth/shopify/callback", "https://openings-simulation-blocking-rational.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
